stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  image: node:14
  script: 
    - yarn install
    - yarn run build
  artifacts: 
    paths:
        - dist/

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk update && apk add openssh-client rsync
    - echo "$RSYNC_PWD" > /rsyncd.pass
    - chmod 600 /rsyncd.pass
  script:
    - rsync --port=8773 -avz -I --password-file=/rsyncd.pass --delete --progress ./dist rsync@pangu.sends.cc::graduate